quarkus:
  http:
    enabled: false
  lambda:
    handler: notifyAdmin
  rest-client:
    feedback-app-api:
      url: http://localhost:8081
      headers:
        Authorization: Basic YWRtaW5AZW1haWwuY29tOmFkbWlu

  mailer:
    from: "gabrieldears@gmail.com"
    host: "smtp.gmail.com"
    port: 587
    username: "gabrieldears@gmail.com"
    password: "xzqp btbu torv hehk"
    start-tls: OPTIONAL
